# Part 1 - Concepts

*1. Read about the database we’ll use below (part II). Give an example for each letter in the CRUD acronym in the context of this database. (3 pts)*
* **Create**:
    - Adds new data to a table in the database.
    - Inserting a new player record into the Players table.
* **Read**:
    - Retrieves specific data from the database based on given conditions.
    - Querying the 'Teams' table to fetch information about teams that played in 2015.
* **Update**:
    - Modifies existing data in the database.
    - An example would be changing a player's name in the 'HallOfFame' table.
* **Delete**:
    - Removes data from the database.
    - Deleting a specific player’s record from the database.

*2. What is the purpose of the `HAVING` clause when writing SQL code? (3 pts)*

The `HAVING` clause filters aggregated results processed using an aggregate function. It is commonly used alongside `GROUP BY` in SQL to apply conditions to grouped data.Unlike `WHERE`, which filters individual rows before aggregation, `HAVING` is applied after the data has been grouped and aggregated.For example, in the Teams table, if the goal is to display only teams with a total win count of 90 or more, `HAVING` would be necessary. Since `WHERE` operates on raw data before aggregation, it cannot be used for this purpose. In summary, `HAVING` is essential for refining grouped data after applying aggregation functions.

# Part 2 - Querying a database

##### Q1.

*Connect to the database and then look at all of the tables in the database (use read_sql() from pandas to have this returned as a data frame). (2 pts)*

In [ ]:
# bring in the module
import sqlite3
import pandas as pd

In [ ]:
# make the connection to the file
con = sqlite3.connect('/content/lahman_1871-2022.sqlite')

In [ ]:
# create a 'cursor' object from connection
cursor = con.cursor()

# create the SQL string
get_schema = '''
             SELECT *
             FROM sqlite_schema
             WHERE type = "table";
             '''
# execute the query
cursor.execute(get_schema)

# grab the result
result = cursor.fetchall()

# close the cursor
cursor.close()

In [ ]:
# convert result into a DataFrame
schema_df = pd.DataFrame(result)
schema_df

,0,1,2,3,4
0,table,AllstarFull,AllstarFull,2,"CREATE TABLE AllstarFull (\nplayerID TEXT,\nye..."
1,table,Appearances,Appearances,3,"CREATE TABLE Appearances (\nyearID INTEGER,\nt..."
2,table,AwardsManagers,AwardsManagers,4,"CREATE TABLE AwardsManagers (\nplayerID TEXT,\..."
3,table,AwardsPlayers,AwardsPlayers,5,"CREATE TABLE AwardsPlayers (\nplayerID TEXT,\n..."
4,table,AwardsShareManagers,AwardsShareManagers,6,CREATE TABLE AwardsShareManagers (\nawardID TE...
5,table,AwardsSharePlayers,AwardsSharePlayers,7,CREATE TABLE AwardsSharePlayers (\nawardID TEX...
6,table,Batting,Batting,8,"CREATE TABLE Batting (\nplayerID TEXT,\nyearID..."
7,table,BattingPost,BattingPost,9,"CREATE TABLE BattingPost (\nyearID INTEGER,\nr..."
8,table,CollegePlaying,CollegePlaying,10,"CREATE TABLE CollegePlaying (\nplayerID TEXT,\..."
9,table,Fielding,Fielding,11,"CREATE TABLE Fielding (\nplayerID TEXT,\nyearI..."
10,table,FieldingOF,FieldingOF,12,"CREATE TABLE FieldingOF (\nplayerID TEXT,\nyea..."
11,table,FieldingOFsplit,FieldingOFsplit,13,"CREATE TABLE FieldingOFsplit (\nplayerID TEXT,..."
12,table,FieldingPost,FieldingPost,14,"CREATE TABLE FieldingPost (\nplayerID TEXT,\ny..."
13,table,HallOfFame,HallOfFame,15,"CREATE TABLE HallOfFame (\nplayerID TEXT,\nyea..."
14,table,HomeGames,HomeGames,16,"CREATE TABLE HomeGames (\nyearkey INTEGER,\nle..."
15,table,Managers,Managers,17,"CREATE TABLE Managers (\nplayerID TEXT,\nyearI..."
16,table,ManagersHalf,ManagersHalf,18,"CREATE TABLE ManagersHalf (\nplayerID TEXT,\ny..."
17,table,Parks,Parks,19,"CREATE TABLE Parks (\nID INTEGER,\nparkalias T..."
18,table,People,People,21,"CREATE TABLE People (\nID INTEGER,\nplayerID T..."
19,table,Pitching,Pitching,23,"CREATE TABLE Pitching (\nplayerID TEXT,\nyearI..."
20,table,PitchingPost,PitchingPost,24,"CREATE TABLE PitchingPost (\nplayerID TEXT,\ny..."
21,table,Salaries,Salaries,25,"CREATE TABLE Salaries (\nyearID INTEGER,\nteam..."
22,table,Schools,Schools,26,"CREATE TABLE Schools (\nschoolID TEXT,\nname_f..."
23,table,SeriesPost,SeriesPost,27,"CREATE TABLE SeriesPost (\nyearID INTEGER,\nro..."
24,table,Teams,Teams,28,"CREATE TABLE Teams (\nyearID INTEGER,\nlgID TE..."
25,table,TeamsFranchises,TeamsFranchises,29,"CREATE TABLE TeamsFranchises (\nfranchID TEXT,..."
26,table,TeamsHalf,TeamsHalf,30,"CREATE TABLE TeamsHalf (\nyearID INTEGER,\nlgI..."

In [ ]:
# another method to retrieve the schema information using read_sql
schema_df2 = pd.read_sql(get_schema, con)
schema_df2

,type,name,tbl_name,rootpage,sql
0,table,AllstarFull,AllstarFull,2,"CREATE TABLE AllstarFull (\nplayerID TEXT,\nye..."
1,table,Appearances,Appearances,3,"CREATE TABLE Appearances (\nyearID INTEGER,\nt..."
2,table,AwardsManagers,AwardsManagers,4,"CREATE TABLE AwardsManagers (\nplayerID TEXT,\..."
3,table,AwardsPlayers,AwardsPlayers,5,"CREATE TABLE AwardsPlayers (\nplayerID TEXT,\n..."
4,table,AwardsShareManagers,AwardsShareManagers,6,CREATE TABLE AwardsShareManagers (\nawardID TE...
5,table,AwardsSharePlayers,AwardsSharePlayers,7,CREATE TABLE AwardsSharePlayers (\nawardID TEX...
6,table,Batting,Batting,8,"CREATE TABLE Batting (\nplayerID TEXT,\nyearID..."
7,table,BattingPost,BattingPost,9,"CREATE TABLE BattingPost (\nyearID INTEGER,\nr..."
8,table,CollegePlaying,CollegePlaying,10,"CREATE TABLE CollegePlaying (\nplayerID TEXT,\..."
9,table,Fielding,Fielding,11,"CREATE TABLE Fielding (\nplayerID TEXT,\nyearI..."
10,table,FieldingOF,FieldingOF,12,"CREATE TABLE FieldingOF (\nplayerID TEXT,\nyea..."
11,table,FieldingOFsplit,FieldingOFsplit,13,"CREATE TABLE FieldingOFsplit (\nplayerID TEXT,..."
12,table,FieldingPost,FieldingPost,14,"CREATE TABLE FieldingPost (\nplayerID TEXT,\ny..."
13,table,HallOfFame,HallOfFame,15,"CREATE TABLE HallOfFame (\nplayerID TEXT,\nyea..."
14,table,HomeGames,HomeGames,16,"CREATE TABLE HomeGames (\nyearkey INTEGER,\nle..."
15,table,Managers,Managers,17,"CREATE TABLE Managers (\nplayerID TEXT,\nyearI..."
16,table,ManagersHalf,ManagersHalf,18,"CREATE TABLE ManagersHalf (\nplayerID TEXT,\ny..."
17,table,Parks,Parks,19,"CREATE TABLE Parks (\nID INTEGER,\nparkalias T..."
18,table,People,People,21,"CREATE TABLE People (\nID INTEGER,\nplayerID T..."
19,table,Pitching,Pitching,23,"CREATE TABLE Pitching (\nplayerID TEXT,\nyearI..."
20,table,PitchingPost,PitchingPost,24,"CREATE TABLE PitchingPost (\nplayerID TEXT,\ny..."
21,table,Salaries,Salaries,25,"CREATE TABLE Salaries (\nyearID INTEGER,\nteam..."
22,table,Schools,Schools,26,"CREATE TABLE Schools (\nschoolID TEXT,\nname_f..."
23,table,SeriesPost,SeriesPost,27,"CREATE TABLE SeriesPost (\nyearID INTEGER,\nro..."
24,table,Teams,Teams,28,"CREATE TABLE Teams (\nyearID INTEGER,\nlgID TE..."
25,table,TeamsFranchises,TeamsFranchises,29,"CREATE TABLE TeamsFranchises (\nfranchID TEXT,..."
26,table,TeamsHalf,TeamsHalf,30,"CREATE TABLE TeamsHalf (\nyearID INTEGER,\nlgI..."

##### Q2.

*Write an SQL query using pd.read_sql() that returns all the teams that played in the year 2015 with all of the corresponding columns from the Teams table. (2 pts)*

Let's write an SQL query to retrieve all teams that played in 2015. This query extracts only the data where yearID is 2015 from the Teams table.

In [ ]:
teams_2015 = pd.read_sql("SELECT * FROM Teams WHERE yearID = 2015", con)
teams_2015

,yearID,lgID,teamID,franchID,divID,Rank,G,Ghome,W,L,...,DP,FP,name,park,attendance,BPF,PPF,teamIDBR,teamIDlahman45,teamIDretro
0,2015,AL,BAL,BAL,E,3,162,78,81,81,...,134,0.987,Baltimore Orioles,Oriole Park at Camden Yards,2281202,103,104,BAL,BAL,BAL
1,2015,AL,BOS,BOS,E,5,162,81,78,84,...,148,0.984,Boston Red Sox,Fenway Park II,2880694,104,107,BOS,BOS,BOS
2,2015,AL,CHA,CHW,C,4,162,81,76,86,...,159,0.983,Chicago White Sox,U.S. Cellular Field,1755810,92,93,CHW,CHA,CHA
3,2015,AL,CLE,CLE,C,3,161,80,81,80,...,136,0.987,Cleveland Indians,Progressive Field,1388905,106,106,CLE,CLE,CLE
4,2015,AL,DET,DET,C,5,161,81,74,87,...,165,0.986,Detroit Tigers,Comerica Park,2726048,97,98,DET,DET,DET
5,2015,AL,HOU,HOU,W,2,162,81,86,76,...,131,0.986,Houston Astros,Minute Maid Park,2153585,97,99,HOU,HOU,HOU
6,2015,AL,KCA,KCR,C,1,162,81,95,67,...,138,0.985,Kansas City Royals,Kauffman Stadium,2708549,104,103,KCR,KCA,KCA
7,2015,AL,LAA,ANA,W,3,162,81,85,77,...,108,0.984,Los Angeles Angels of Anaheim,Angel Stadium of Anaheim,3012765,94,95,LAA,ANA,ANA
8,2015,AL,MIN,MIN,C,2,162,81,83,79,...,150,0.986,Minnesota Twins,Target Field,2220054,103,104,MIN,MIN,MIN
9,2015,AL,NYA,NYY,E,2,162,81,87,75,...,135,0.985,New York Yankees,Yankee Stadium III,3193795,99,101,NYY,NYA,NYA
10,2015,AL,OAK,OAK,W,5,162,81,68,94,...,154,0.979,Oakland Athletics,O.co Coliseum,1768175,97,98,OAK,OAK,OAK
11,2015,AL,SEA,SEA,W,4,162,81,76,86,...,155,0.985,Seattle Mariners,Safeco Field,2193581,92,94,SEA,SEA,SEA
12,2015,AL,TBA,TBD,E,4,162,84,80,82,...,118,0.984,Tampa Bay Rays,Tropicana Field,1287054,100,102,TBR,TBA,TBA
13,2015,AL,TEX,TEX,W,1,162,81,88,74,...,169,0.981,Texas Rangers,Globe Life Park in Arlington,2491875,102,105,TEX,TEX,TEX
14,2015,AL,TOR,TOR,E,1,162,81,93,69,...,145,0.985,Toronto Blue Jays,Rogers Centre,2794891,99,98,TOR,TOR,TOR
15,2015,NL,ARI,ARI,W,3,162,81,79,83,...,146,0.986,Arizona Diamondbacks,Chase Field,2080145,107,106,ARI,ARI,ARI
16,2015,NL,ATL,ATL,E,4,162,81,67,95,...,186,0.985,Atlanta Braves,Turner Field,2001392,97,97,ATL,ATL,ATL
17,2015,NL,CHN,CHC,C,3,162,81,97,65,...,120,0.982,Chicago Cubs,Wrigley Field,2919122,100,100,CHC,CHN,CHN
18,2015,NL,CIN,CIN,C,5,162,81,64,98,...,131,0.985,Cincinnati Reds,Great American Ball Park,2419506,101,101,CIN,CIN,CIN
19,2015,NL,COL,COL,W,5,162,81,68,94,...,171,0.985,Colorado Rockies,Coors Field,2506789,119,118,COL,COL,COL
20,2015,NL,LAN,LAD,W,1,162,81,92,70,...,133,0.988,Los Angeles Dodgers,Dodger Stadium,3764815,101,98,LAD,LAN,LAN
21,2015,NL,MIA,FLA,E,3,162,81,71,91,...,162,0.987,Miami Marlins,Marlins Park,1752235,98,97,MIA,FLO,MIA
22,2015,NL,MIL,MIL,C,4,162,81,68,94,...,164,0.981,Milwaukee Brewers,Miller Park,2542558,101,101,MIL,ML4,MIL
23,2015,NL,NYN,NYM,E,1,162,81,90,72,...,131,0.986,New York Mets,Citi Field,2569753,94,92,NYM,NYN,NYN
24,2015,NL,PHI,PHI,E,5,162,81,63,99,...,145,0.981,Philadelphia Phillies,Citizens Bank Park,1831080,98,98,PHI,PHI,PHI
25,2015,NL,PIT,PIT,C,2,162,81,98,64,...,177,0.981,Pittsburgh Pirates,PNC Park,2498596,99,97,PIT,PIT,PIT
26,2015,NL,SDN,SDP,W,4,162,81,74,88,...,138,0.985,San Diego Padres,Petco Park,2459742,98,97,SDP,SDN,SDN
27,2015,NL,SFN,SFG,W,2,162,81,84,78,...,145,0.987,San Francisco Giants,AT&T Park,3375882,99,97,SFG,SFN,SFN
28,2015,NL,SLN,STL,C,1,162,81,100,62,...,159,0.984,St. Louis Cardinals,Busch Stadium III,3520889,102,101,STL,SLN,SLN
29,2015,NL,WAS,WSN,E,2,162,81,83,79,...,125,0.985,Washington Nationals,Nationals Park,2619843,102,99,WSN,MON,WAS

##### Q3.

*Write an SQL query using pd.read_sql() that returns all of the players in the hall of fame, the year they were voted into the hall of fame, and their category- see the HallOfFame table, the inducted variable is important here. (3 pts)*

Before solving this problem, let's check the information in the HallOfFame table.

In [ ]:
hall_of_fame = pd.read_sql("SELECT * FROM HallOfFame", con)
hall_of_fame

,playerID,yearid,votedBy,ballots,needed,votes,inducted,category,needed_note
0,aaronha01,1982,BBWAA,415.0,312.0,406.0,Y,Player,None
1,abbotji01,2005,BBWAA,516.0,387.0,13.0,N,Player,None
2,abreubo01,2020,BBWAA,397.0,298.0,22.0,N,Player,None
3,abreubo01,2021,BBWAA,401.0,301.0,35.0,N,Player,None
4,abreubo01,2022,BBWAA,394.0,296.0,34.0,N,Player,None
...,...,...,...,...,...,...,...,...,...
4318,zambrca01,2018,BBWAA,422.0,317.0,0.0,N,Player,None
4319,zeileto01,2010,BBWAA,539.0,405.0,0.0,N,Player,None
4320,zimmech01,1938,BBWAA,262.0,197.0,1.0,N,Player,None
4321,ziskri01,1989,BBWAA,447.0,336.0,0.0,N,Player,None
4322,zitoba01,2021,BBWAA,401.0,301.0,1.0,N,Player,None

 Return playerID, yearID, and category from the HallOfFame table, filtering the inducted column for values equal to 'Y' to identify inducted players.

In [ ]:
hall_of_fame_players = pd.read_sql("SELECT playerID, yearid, category FROM HallOfFame WHERE inducted = 'Y'", con)
hall_of_fame_players

      playerID  yearid           category
0    aaronha01    1982             Player
1    alexape01    1938             Player
2    alomaro01    2011             Player
3    alstowa01    1983            Manager
4    andersp01    2000            Manager
..         ...     ...                ...
335  yastrca01    1989             Player
336  yawketo99    1980  Pioneer/Executive
337  youngcy01    1937             Player
338  youngro01    1972             Player
339  yountro01    1999             Player

[340 rows x 3 columns]

##### Q4.

*Write an SQL query using pd.read_sql() that return all unique managers of the Pittsburgh Pi rates (teamID of PIT) and only that information from the Managers table. Hint: Check out SELECT DISTINCT (3 pts)*

Next, check the information in the Managers table.

In [ ]:
managers = pd.read_sql("SELECT * FROM Managers", con)
managers

       playerID  yearID teamID lgID  inseason    G   W    L  rank plyrMgr
0     wrighha01    1871    BS1   NA         1   31  20   10     3       Y
1      woodji01    1871    CH1   NA         1   28  19    9     2       Y
2     paborch01    1871    CL1   NA         1   29  10   19     8       Y
3     lennobi01    1871    FW1   NA         1   14   5    9     8       Y
4     deaneha01    1871    FW1   NA         2    5   2    3     8       Y
...         ...     ...    ...  ...       ...  ...  ..  ...   ...     ...
3713  woodwch01    2022    TEX   AL         1  114  51   63     4       N
3714  beaslto99    2022    TEX   AL         2   48  17   31     4       N
3715  montoch01    2022    TOR   AL         1   88  46   42     2       N
3716  schnejo99    2022    TOR   AL         2   74  46   28     2       N
3717  martida01    2022    WAS   NL         1  162  55  107     5       N

[3718 rows x 10 columns]

Use SELECT DISTINCT to ensure that duplicate playerID values are not included. Additionally, filter the results to include only managers who worked in Pittsburgh by specifying teamID = 'PIT'.

In [ ]:
managers_PIT = pd.read_sql("SELECT DISTINCT playerID FROM Managers WHERE teamID = 'PIT'", con)
managers_PIT

     playerID
0   bezdehu99
1   bragabo01
2   buckeal99
3   burnsto01
4   burwebi01
5    bushdo01
6   callani01
7   clarkfr01
8   davissp01
9   donovpa01
10  dunlafr01
11    ensje01
12  friscfr01
13  gibsoge01
14  grammal01
15  haneyfr01
16  hanlone01
17  heckegu01
18  hermabi01
19  hurdlcl01
20  lamonge01
21  leylaji99
22  mackape01
23   mackco01
24  mcclell01
25  mcgunbi01
26  mckecbi01
27  meyerbi01
28  murtada01
29  phillho99
30  princto01
31  russejo02
32  sheltde99
33  shepala99
34  tannech01
35  tracyji01
36  traynpi01
37  virdobi01
38  wagneho01
39  walkeha01
40  watkibi01

##### Q5.

*Use SQL code and the HallOfFame and Managers tables to return all of the playerIDs for the people that managed for a team that were inducted into the hall of fame. Also, programmatically report the number of such people- this can be done in pandas after returning the data from the call to pd.read_sql(). (4 pts)*

In this section, `pd.merge()` is used. First, retrieve playerID from the Managers table without duplicates. Next, retrieve the inducted playerID from the HallOfFame table. Then, perform an inner merge of these two datasets based on playerID.

In [ ]:
fame_managers = pd.merge(left = pd.read_sql("SELECT DISTINCT playerID FROM Managers", con),
                         right = pd.read_sql("SELECT playerID FROM HallOfFame WHERE inducted = 'Y'", con),
                         how = "inner", on = "playerID")
fame_managers

     playerID
0   alstowa01
1   andersp01
2   ansonca01
3   applilu01
4   baineha01
..        ...
92  willidi02
93  willite01
94  wrighge01
95  wrighha01
96  youngcy01

[97 rows x 1 columns]

The total number of managers can be checked using `len()`.

In [ ]:
len(fame_managers)

97

##### Q6.

*Now use the same two tables (HallOfFame and Managers) and an SQL query to return every season managed by each manager that made it to the hall of fame (so do this with an SQL join, not via pd.merge()). You should return the playerID (manager ID), G, W, and L columns from the Managers table.*

*Second, determine the overall win/loss records (sum of wins and sum of losses) for each of these hall of fame managers. Third, create a new variable that is the win/loss percentage (W/(W+L)). Lastly, sort the resulting data by the win/loss percentage variable (from largest to smallest). The last three parts can be done in pandas with the returned data or you can do it via SQL in your call to pd.read_sql().(6 pts)*

Assign the alias M to Managers and H to HallOfFame. Using these aliases, retrieve playerID, G, W, and L from M, and join the results with the inducted playerID from H using JOIN.

In [ ]:
every_season = pd.read_sql("SELECT M.playerID, M.G, M.W, M.L FROM Managers M JOIN HallOfFame H ON M.playerID = H.playerID WHERE H.inducted = 'Y'", con)
every_season

      playerID    G   W   L
0    alstowa01  154  92  62
1    alstowa01  154  98  55
2    alstowa01  154  93  61
3    alstowa01  154  84  70
4    alstowa01  154  71  83
..         ...  ...  ..  ..
991  wrighha01   46  22  23
992  wrighha01  138  68  69
993  wrighha01  155  87  66
994  wrighha01  133  72  57
995  youngcy01    6   3   3

[996 rows x 4 columns]

The total win-loss record, win rate calculation, and sorting in descending order are handled using pandas. Store the aggregated win-loss record in total_win_loss, then use this information to calculate the win rate. Finally, use sort_values() to sort the data in descending order based on the win rate.

In [ ]:
total_win_loss = every_season.groupby("playerID")[["W", "L"]].sum()

total_win_loss["Win_Percentage"] = total_win_loss["W"] / (total_win_loss["W"] + total_win_loss["L"])

total_win_loss.sort_values(by = "Win_Percentage", ascending = False)

              W     L  Win_Percentage
playerID
simmote01     1     0        1.000000
wrighge01    59    25        0.702381
spaldal01    78    47        0.624000
mccarjo99  2125  1333        0.614517
comisch01   840   541        0.608255
...         ...   ...             ...
bottoji01    21    56        0.272727
baineha01     1     3        0.250000
applilu01    10    30        0.250000
wagneho01     1     4        0.200000
connoro01     8    37        0.177778

[97 rows x 3 columns]

##### Q7.

*I’m going to give less guidance on this one but it will be similar to the above! Using SQL, construct a table of hall of fame pitchers (any hall of famer that pitched) that gives the playerID and their total (sum) for GS, G, W, L, IPOuts, CG, SHO, and SV columns. The summing can be done in pandas or in the SQL call. (6 pts)*

Examine the information in the Pitching table.

In [ ]:
pitching = pd.read_sql("SELECT * FROM Pitching", con)
pitching

,playerID,yearID,stint,teamID,lgID,W,L,G,GS,CG,...,IBB,WP,HBP,BK,BFP,GF,R,SH,SF,GIDP
0,aardsda01,2004,1,SFN,NL,1,0,11,0,0,...,0.0,0,2.0,0,61.0,5,8,0.0,1.0,1.0
1,aardsda01,2006,1,CHN,NL,3,0,45,0,0,...,0.0,1,1.0,0,225.0,9,25,1.0,3.0,2.0
2,aardsda01,2007,1,CHA,AL,2,1,25,0,0,...,3.0,2,1.0,0,151.0,7,24,2.0,1.0,1.0
3,aardsda01,2008,1,BOS,AL,4,2,47,0,0,...,2.0,3,5.0,0,228.0,7,32,3.0,2.0,4.0
4,aardsda01,2009,1,SEA,AL,3,6,73,0,0,...,3.0,2,0.0,0,296.0,53,23,2.0,1.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50397,zuverge01,1958,1,BAL,AL,2,2,45,0,0,...,3.0,2,6.0,0,294.0,23,29,NaN,NaN,NaN
50398,zuverge01,1959,1,BAL,AL,0,1,6,0,0,...,0.0,1,0.0,0,55.0,1,7,NaN,NaN,NaN
50399,zychto01,2015,1,SEA,AL,0,0,13,1,0,...,0.0,1,2.0,0,76.0,4,6,0.0,0.0,0.0
50400,zychto01,2016,1,SEA,AL,1,0,12,0,0,...,2.0,0,1.0,0,60.0,3,6,0.0,1.0,1.0
50401,zychto01,2017,1,SEA,AL,6,3,45,0,0,...,3.0,1,5.0,1,173.0,7,12,1.0,2.0,5.0

 Assign the alias P. Using this alias, retrieve the columns GS, G, W, L, IPOuts, CG, SHO, and SV, and then combine the results with the list of inducted pitchers. Use JOIN for this process.

In [ ]:
fame_pitchers_row = """
                    SELECT p.playerID, p.GS, p.G, p.W, p.L, p.IPOuts, p.CG, p.SHO, p.SV
                    FROM Pitching p
                    JOIN HallOfFame h ON p.playerID = h.playerID
                    WHERE h.inducted = 'Y';
                    """

fame_pitchers = pd.read_sql(fame_pitchers_row, con)
fame_pitchers

       playerID  GS   G   W   L  IPouts  CG  SHO  SV
0     alexape01  37  48  28  13    1101  31    7   3
1     alexape01  34  46  19  17     931  25    3   3
2     alexape01  36  47  22   8     919  23    9   2
3     alexape01  39  46  27  15    1065  32    6   1
4     alexape01  42  49  31  10    1129  36   12   3
...         ...  ..  ..  ..  ..     ...  ..  ...  ..
1507  youngcy01  33  36  21  11     897  30    3   2
1508  youngcy01  34  35  19  15     883  30    3   0
1509  youngcy01  20  21   7  10     490  14    1   0
1510  youngcy01   7   7   3   4     139   4    0   0
1511  youngcy01  11  11   4   5     240   8    2   0

[1512 rows x 9 columns]

Next, calculate the sum of each column using pandas, grouped by playerID.

In [ ]:
fame_pitchers_sum = fame_pitchers.groupby("playerID")[["GS", "G", "W", "L", "IPouts", "CG", "SHO", "SV"]].sum()
fame_pitchers_sum

            GS    G    W    L  IPouts   CG  SHO  SV
playerID
alexape01  599  696  373  208   15570  437   90  32
ansonca01    0    3    0    1      12    0    0   1
becklja01    1    1    0    1      12    0    0   0
bendech01  334  459  212  127    9051  255   40  34
blylebe01  685  692  287  250   14910  242   60   0
...        ...  ...  ...  ...     ...  ...  ...  ..
willivi01  471  513  249  205   11988  388   50  11
wrighge01    0    3    0    1      15    0    0   0
wrighha01    8   36    4    4     301    0    0  14
wynnea01   612  691  300  244   13692  290   49  15
youngcy01  815  906  511  315   22068  749   76  18

[108 rows x 8 columns]

##### Q8.

*For all of the hall of fame pitchers, use SQL to create a table of their batting statistics. Namely, the playerID and their total (sum) for AB, R, H, HR, RBI, BB, and SO. The summing can be done in pandas or in the SQL call. (4 pts)*

Retrieve the information from the Batting table.

In [ ]:
batting = pd.read_sql("SELECT * FROM Batting", con)
batting

,playerID,yearID,stint,teamID,lgID,G,G_batting,AB,R,H,...,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP,G_old
0,aardsda01,2004,1,SFN,NL,11,None,0,0,0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,None
1,aardsda01,2006,1,CHN,NL,45,None,2,0,0,...,0.0,0.0,0,0.0,0.0,0.0,1.0,0.0,0.0,None
2,aardsda01,2007,1,CHA,AL,25,None,0,0,0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,None
3,aardsda01,2008,1,BOS,AL,47,None,1,0,0,...,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0,None
4,aardsda01,2009,1,SEA,AL,73,None,0,0,0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112179,zwilldu01,1915,1,CHF,FL,150,None,548,65,157,...,24.0,NaN,67,65.0,NaN,2.0,18.0,NaN,NaN,None
112180,zwilldu01,1916,1,CHN,NL,35,None,53,4,6,...,0.0,NaN,4,6.0,NaN,0.0,2.0,NaN,NaN,None
112181,zychto01,2015,1,SEA,AL,13,None,0,0,0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,None
112182,zychto01,2016,1,SEA,AL,12,None,0,0,0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,None
112183,zychto01,2017,1,SEA,AL,45,None,0,0,0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,None

Assign the alias B. Using this alias, retrieve the columns AB, R, H, HR, RBI, BB, and SO, and then combine the results with the list of inducted pitchers. Use JOIN for this process.

In [ ]:
fame_batting_row = """
                    SELECT b.playerID, b.AB, b.R, b.H, b.HR, b.RBI, b.BB, b.SO
                    FROM Batting b
                    JOIN HallOfFame h ON b.playerID = h.playerID
                    WHERE h.inducted = 'Y';
                    """

fame_batting = pd.read_sql(fame_batting_row, con)
fame_batting

       playerID   AB    R    H  HR    RBI  BB    SO
0     aaronha01  468   58  131  13   69.0  28  39.0
1     aaronha01  602  105  189  27  106.0  49  61.0
2     aaronha01  609  106  200  26   92.0  37  54.0
3     aaronha01  615  118  198  44  132.0  57  58.0
4     aaronha01  601  109  196  30   95.0  59  49.0
...         ...  ...  ...  ...  ..    ...  ..   ...
4779  yountro01  614  101  195  21  103.0  63  71.0
4780  yountro01  587   98  145  17   77.0  78  89.0
4781  yountro01  503   66  131  10   77.0  54  79.0
4782  yountro01  557   71  147   8   77.0  53  81.0
4783  yountro01  454   62  117   8   51.0  44  93.0

[4784 rows x 8 columns]

Finally, calculate the sum of each column using pandas, grouped by playerID.

In [ ]:
fame_batting_sum = fame_batting.groupby("playerID")[["AB", "R", "H", "HR", "RBI", "BB", "SO"]].sum()
fame_batting_sum

              AB     R     H   HR     RBI    BB      SO
playerID
aaronha01  12364  2174  3771  755  2297.0  1402  1383.0
alexape01   1810   154   378   11   163.0    77   276.0
alomaro01   9073  1508  2724  210  1134.0  1032  1140.0
alstowa01      1     0     0    0     0.0     0     1.0
andersp01    477    42   104    0    34.0    42    53.0
...          ...   ...   ...  ...     ...   ...     ...
wynnea01    1704   136   365   17   173.0   141   330.0
yastrca01  11988  1816  3419  452  1844.0  1845  1393.0
youngcy01   2960   325   623   18   290.0    81   381.0
youngro01   4627   812  1491   42   592.0   550   390.0
yountro01  11008  1632  3142  251  1406.0   966  1350.0

[271 rows x 7 columns]

##### Q9.

*Using pandas join the previous two tables together by pitcher. (If you want, try to do all of this via SQL! Not required though, feel free to use pd.merge() if you’d like) (4 pts)*

In [ ]:
pitchers_batting = fame_pitchers_sum.merge(fame_batting_sum, on="playerID")
pitchers_batting

,GS,G,W,L,IPouts,CG,SHO,SV,AB,R,H,HR,RBI,BB,SO
playerID,,,,,,,,,,,,,,,
alexape01,599,696,373,208,15570,437,90,32,1810,154,378,11,163.0,77,276.0
ansonca01,0,3,0,1,12,0,0,1,10281,1999,3435,97,2075.0,984,330.0
becklja01,1,1,0,1,12,0,0,0,9551,1603,2938,87,1581.0,616,526.0
bendech01,334,459,212,127,9051,255,40,34,1147,102,243,6,116.0,75,143.0
blylebe01,685,692,287,250,14910,242,60,0,451,19,59,0,25.0,5,193.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
willivi01,471,513,249,205,11988,388,50,11,1493,107,248,1,84.0,81,199.0
wrighge01,0,3,0,1,15,0,0,0,2873,665,866,11,326.0,68,119.0
wrighha01,8,36,4,4,301,0,0,14,813,183,224,4,113.0,37,14.0
wynnea01,612,691,300,244,13692,290,49,15,1704,136,365,17,173.0,141,330.0
youngcy01,815,906,511,315,22068,749,76,18,2960,325,623,18,290.0,81,381.0